In [1]:
from glassdoor_scraper import get_job_posts

In [2]:
jobs = get_job_posts('Data Scientist', 'Portland')

Searching Glassdoor for  Data Scientist openings in Portland
Fetching location details
Total job pages found: 7
Total job listings found: 196

In [7]:
jobs['Company'] = jobs['Company'].apply(lambda x : x[0])

In [8]:
jobs

,Company,Job Title,Location,Rating,Salary,Description
0,ProKarma,Data Scientist,"Portland, OR",,"136,000",Description ProKarma is currently seeking a D...
1,The Standard,Data Scientist,"Portland, OR",,"106,000",Overview If you want to make a positive diffe...
2,DiscoverOrg,Data Scientist,"Vancouver, WA",,"112,000",Do you consider yourself a Data Scientist or ...
3,Simple,Data Scientist,"Portland, OR",,"112,000",The Company: We're a tech company that's chan...
4,First Tech Federal Credit Union,Quantitative Data Analyst,"Hillsboro, OR",,"62,000",Our Enterprise Risk department is looking for ...
5,Goldstar,Data Scientist - Machine Learning,"Portland, OR",,"154,000",Goldstar is looking for an experienced data s...
6,Nike,"Data Scientist, Personalization","Portland, OR",,"154,000","Become a Part of the NIKE, Inc. Team NIKE, ..."
7,Slalom LLC.,Data Scientist,"Portland, OR",,"145,000","Job Title: Data Scientist, Data & Analytics ..."
8,First Tech Federal Credit Union,Senior Data Scientist,"Hillsboro, OR",,"132,000",We’re looking for a Senior Data Scientist to j...
9,Vesta Corporation,Data Scientist,"Lake Oswego, OR",,"109,000",We are looking for a Data Scientist to beco...
10,ProKarma,Analytics Consultant,"Portland, OR",,"95,000",Description ProKarma is currently seeking an ...
11,Diverse Lynx,Data Scientist,"Portland, OR",,"124,000",Responsibilities: Design and implement distrib...
12,General Assembly,Data Scientist - Relocation Opportunity,"Portland, OR",,"128,000",General Assembly (GA) is a global educational...
13,comScore,Data Analyst - Custom Analytics,"Portland, OR",,"68,000",Job Description Job Title : Data Analyst – Cu...
14,Apex Systems,Data Scientist,"Portland, OR",,NaN,Job DescriptionJob #: 918239 Position: Data...
15,Profocus Technology,Data Scientist - R Shiny,"Beaverton, OR",,NaN,POSITION TITLE Data Scientist OVERVIEW: ProFo...
16,Oracle,2018-19 College Recruiting Data Scientist,"Portland, OR",,"129,000","Designs, develops and programs methods, proce..."
17,VanderHouwen,Data Analyst,"Beaverton, OR",,NaN,Job ID: 37907 ***Not able to use 3rd Party Age...
18,Yieldbot,Data Scientist,"Portland, OR",,"117,000",Data Scientist Location: Portland Share Ab...
19,Nike,Senior Data Scientist,"Portland, OR",,"162,000",Work cross-functionally with research scientis...
20,CoStar Group,Data Analyst,"Portland, OR",,"73,000",Data Analyst Job Description Data Analyst ...
21,Nike,Sr Data Scientist,"Portland, OR",,"162,000","Job DescriptionInnovation is oxygen for Nike,..."
22,Cambia Health Solutions,Data Scientist - Deep Learning,"Portland, OR",,"181,000","Data Scientist - Deep Learning Portland, OR We..."
23,Kroger,Technology - Data Scientist,"Portland, OR",,"113,000",Company Name: Kroger General Office Position ...
24,CyberCoders,Data Scientist,"Portland, OR",,NaN,Data Scientist If you are a Data Scientist ...
25,DataRobot,Customer Facing Data Scientist,"Portland, OR",,NaN,Customer Facing Data Scientists work with the...
26,Simple,Data Engineer,"Portland, OR",,"137,000",The Company We're a tech company that's chang...
27,First Tech Federal Credit Union,Deposit Products Data Analyst,"Hillsboro, OR",,"62,000",We’re looking for an analytical and highly or...
28,VanderHouwen,Business Intelligence Analyst,"Portland, OR",,NaN,Job ID: 37970 ***Not able to use 3rd Party Age...
29,Fisher Investments,Marketing Data Analyst,"Portland, OR",,"67,000",Job Description Overview Global Marketing is...
...,...,...,...,...,...,...
166,Centizen,Data Engineer (Python/Hadoop)-,"Beaverton, OR",,NaN,Position Details: Data Engineer (Python/Hadoo...
167,Intel,"Research Scientist (AI, Application Analyses, ...","Hillsboro, OR",,"129,000",Job Description Come join the Accelerator Arch...
168,Intel,Wireless Research Scientist,"Hillsboro, OR",,"129,000","Job Description Initiates the design, developm..."
169,Umpqua Bank,Capital Planning Modeler/Quantitative Analyst,"Portland, OR",,"76,000",The incumbent will assist in completing model...
170,TEK,Marketing Business Intelligence Analyst,"Beaverton, OR",,"75,000",Marketing Business Intelligence Analyst TEK*...
171,Rishabh RPO,Big Data Engineer,"Hillsboro, OR",,NaN,Title : Big Data Engineer Location : Hillsboro...
172,Macropace Technologies,DATA Analyst (sql server),"Hillsboro, OR",,NaN,"DATA Analyst Hillsboro, OR FTE Position Job ..."
173,Umpqua Bank,Customer Analytics Consultant,"Portland, OR",,"79,000",JOB PURPOSE Analyzes customer activity and be...
174,Kforce,Data Engineer,"Beaverton, OR",,NaN,RESPONSIBILITIES: Kforce has a client in searc...
175,"Genesis Financial Solutions, Inc.",Analytics Manager,"Beaverton, OR",,"76,000",Join the nation’s leader in second-look financ...
176,Umpqua Bank,Capital Planning Modeler/Quantitative Analyst ...,"Portland, OR",,"76,000",The incumbent will assist in completing model...
177,Centizen,Sr Data Science Engineer -,"Hillsboro, OR",,NaN,Position Details: Sr Data Science Engineer - ...
178,Providence Health & Services,Principal Data Engineer - PSJH -,"Portland, OR",,"164,000",Description: Providence is calling a Princip...
179,ServerLogic,Data Engineer Consultant,"Beaverton, OR",,NaN,Our client is looking for a Sr. Data Engineer...
180,Intel,Memory Architecture Research Scientist,"Hillsboro, OR",,"129,000",Job Description The Memory Architecture Lab MA...
181,ServerLogic,Sr Data Engineer,"Beaverton, OR",,NaN,"As a Senior Data Engineer, you will work with..."
182,The Vancouver Clinic,Data Analyst-Revenue,"Vancouver, WA",,"56,000",The Data Analyst for Revenue is responsible f...
183,City of Gresham Oregon,Environmental Data Analyst - Natural Resources,"Gresham, OR",,NaN,Overview The City of Gresham's Natural Resour...
184,Blueocean Market Intelligence,Marketing Data Analyst,"Hillsboro, OR",,"71,000",Job description: It has become increasingly a...
185,CorTech,Data Analyst 1,"Beaverton, OR",,"61,000",Job Description: Competencies Integrity Behav...
186,Intel,"Research Scientist (AI, Application Analyses, ...","Hillsboro, OR",,"129,000",Job Description Come join the Accelerator Arch...
187,Epiq,Senior Data Analyst,"Beaverton, OR",,"151,000",It's fun to work at a company where people tr...
188,Intel,I/O Circuit Research Scientist,"Hillsboro, OR",,"144,000","Job Description In this position, you will be ..."
189,U.S. Bank,Sr Business Intelligence Analyst,"Gresham, OR",,"81,000",Elavon provides end-to-end payment processing...
190,Epiq Class Action & Claims Solutions,Senior Data Analyst,"Beaverton, OR",,NaN,It's fun to work at a company where people tr...
191,Aroghia Group,Big Data Engineer,"Beaverton, OR",,NaN,Company Description The Aroghia Group is a na...
192,CDI Corporation,Data Analyst - Part time,"Hillsboro, OR",,NaN,Part-Time Data Analyst CDI is looking for a...
193,BrainWorks (New Jersey),Sr. Manager of Data Science,"Oregon City, OR",,NaN,Job ID: EB-1157440515 Category: Analytics & ...
194,e-Celtic Limited,Senior Data Engineer,"Beaverton, OR",,NaN,Looking for Senior Data Engineer. Client : ...
195,Kforce,Senior Data Engineer,"Hillsboro, OR",,NaN,RESPONSIBILITIES: Kforce has a client in searc...